FROM php:7.4-cli
WORKDIR /app
COPY kage_protected.so /usr/local/lib/php/extensions/no-debug-non-zts-20190902/kage.so
RUN docker-php-ext-enable kage
COPY . /app
CMD export KAGE_ENCRYPTION_KEY="0123456789abcdef0123456789abcdef" ; \
    php -r " \
        \$key = '0123456789abcdef0123456789abcdef'; \
        \$code = '<?php echo \"[VMP] Protected function execution SUCCESS\\n\"; ?>'; \
        \$enc = kage_encrypt_c(\$code, \$key); \
        file_put_contents('test.kage', base64_decode(\$enc)); \
        include 'test.kage'; \
    "
